### ISSUE TITLE
AYUDAME

### ISSUE THREAD

**Issue by ghost** [canoing/newPro#3]
AYUDA BULA XD SE ME CERRÓ SESIÓN EN EL WHATS Y NO TENGO EN CELULAR PARA
INICIAR DE NUEVO AYUDA BACA XD DILE A ONEIDIS QUE SE VE MEJOR SIN CHINA XDXD AYUDA
BULA NECESITO AYUDA URGENTE

**Comment by canoing** [comment]
Sabes que es público esto xd
